service: sls-dyndns

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1

package:
  include:
    - src/**

functions:
  DynDNS:
    handler: index.handler
    events:
      - http:
          method: get